name: auth service pipeline

on:
  push:
    branches:
    - auth_service
  pull_request:
    branches:
    - auth_service

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install and Run Sherlock Scanner
        run: |
          pip install sherlock-scanner
          sherlock . || true

      - name: Install and Run Bandit
        run: |
          pip install bandit
          bandit -r . -ll || true

      - name: Build Docker Image
        run: |
          docker build -t rebachi/stockpnl:auth .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image to Docker Hub
        run: |
          docker push rebachi/stockpnl:auth 

      - name: Notify on Success
        run: echo "Pipeline is done"